services:

  nagios:
    image: jasonrivers/nagios:latest
    container_name: nagios
    volumes:
      - ./nagios/etc/:/opt/nagios/etc/
      - ./nagios/var:/opt/nagios/var/
      - ./custom-plugins:/opt/Custom-Nagios-Plugins
      - ./nagiosgraph/var:/opt/nagiosgraph/var
      - ./nagiosgraph-/tc:/opt/nagiosgraph/etc
    ports:
      - "8080:80"
    restart: unless-stopped
